### ISSUE TITLE
help permalink have multiple  entries

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/web-geoadmin-help#14]
Currently 
help url looks like
"https://help.geo.admin.ch/?ids=54#/?ids=54&lang=de"
IMHO double entries 

and all permalinks like
http://help.geo.admin.ch/?id=32  

are now broken 
result:
-> all links for school and documention do not work anymore ....quite annoying

expected result
http://help.geo.admin.ch/?id=32&lang=de
http://help.geo.admin.ch/?id=32 
do work as in the past

**Comment by pauloamado** [comment]
Works fine, thx
